name: Saturn VLA spectral inversionn workflow
jobs:
  test-sampling:
    skip: true
    env:
      PROBLEM: saturn_vla
      NLIM: 100
      NODES: 8
      NWALKER: 16
    steps:
      - name: create an input file based on the template
        run: >
          ./create_input.py -M -i $PROBLEM.tmp --nwalker=$NWALKER --nodes=$NODES --nlim=$NLIM 
          -o $NLIM-$NWALKER &> log.$NLIM-$NWALKER
      - name: run program
        run: mpiexec -n $NODES ./$PROBLEM.ex -i $PROBLEM-$NLIM-$NWALKER.inp < /dev/null &>> log.$NLIM-$NWALKER
      - name: combine outputs
        run: ./combine.py &>> log.$NLIM-$NWALKER
  vla-global-inversion:
    env:
      PROBLEM: saturn_vla_inversion
      NLIM: 1000
      NODES: 8
      NWALKER: 16
      SNH3: 1.0
      ZNH3: 20
      PLEVEL: 25.:0.7:6
      NAME: $LATITUDE
    strategy:
      vector:
        #LATITUDE: [44.4]
        #LATITUDE: [0.2, 6.5, 15.7, 21.4, 26.8, 32.1, 38.3, 51.5, 55.8, 61.9, 64., 72.1, 78.1, 81.5, 84.5]
        LATITUDE: [-9.8, -8.5, -6.7, -3.6, -1.1, 0.2, 1.2, 3.4, 4.7, 
                    6.5, 8.8, 9.9, 15.7, 18.3, 19.3, 21.4, 23.4, 25.3,
                    26.8, 28.7, 30.6, 32.1, 34.1, 35.4, 38.3, 39.6, 40.7,
                    43.0, 44.4, 47.4, 48.6, 51.5, 52.5, 53.9, 55.8, 58.5,
                    61.9, 64.0, 65.8, 66.9, 68.6, 72.1, 73.2, 75.1, 78.7, 
                    80.5, 81.5, 83.5, 84.5]
    steps:
      - name: prepare vla observation
        run: >
          ./prepare_saturn_vla.py -i $PROBLEM.tmp
          --sNH3=$SNH3 --zNH3=$ZNH3 --glat=$LATITUDE 
          --nwalker=$NWALKER --nodes=$NODES --nlim=$NLIM --plevel="$PLEVEL"
          -o $NAME &> log.$NAME
      - name: run program
        run: mpiexec -n $NODES ./saturn_vla.release -i $PROBLEM-$NAME.inp < /dev/null &> log.$NAME
      - name: combine outputs
        run: ./combine.py &>> log.$NAME
      - name: move data to archive
        run: mv saturn_vla_inversion-$NAME* /data1/22.SaturnVLA/
  vla-global-analysis:
    skip: true
    needs:
      files:
        - gochs/saturn_vla-latitudes-??-1000-16-1.5.obs
    steps:
      - name: plot global fitting results
        run: ./plot_global_fitting.py
    outpus:
      - figs/global_tb_map.png
